name: Deploy to VPS

on:
  workflow_run:
    workflows: ["Test Backend"]
    types:
      - completed
  workflow_dispatch:  # Permet le déclenchement manuel

jobs:
  deploy:
    if: |
      (github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'workflow_run' && 
       github.event.workflow_run.conclusion == 'success' && 
       github.event.workflow_run.head_branch == 'main')
    runs-on: ubuntu-latest

    steps:
      - name: Debug workflow info
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Workflow run conclusion: ${{ github.event.workflow_run.conclusion }}"
          echo "Head branch: ${{ github.event.workflow_run.head_branch }}"
          echo "Repository: ${{ github.repository }}"
          
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /opt/Waveme
            git config --global --add safe.directory /opt/Waveme

            echo "Fetching remote branches..."
            git fetch origin

            echo "Waiting for latest commit to be available..."
            sleep 15

            echo "Pulling latest changes..."
            git pull origin main

            echo "Getting latest commits..."
            sleep 15

            echo "Restarting containers..."
            docker-compose down --remove-orphans
            docker-compose up -d --build
